import {ReactNode} from 'react'
import type {Metadata} from 'next'
import {Box} from '@mui/material'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: ReactNode
}

export default function RootLayout({children}: Props) {
  return (
    <Box
      component={'html'}
      lang="en"
      sx={{minHeight: '100vh', margin: 0}}
    >
      <Box
        component={'body'}
        sx={{minHeight: '100vh', margin: 0}}
      >
        {children}
      </Box>
    </Box>
  )
}
